# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      major:
        update-types: [major]
      minor-patch:
        update-types: [minor, patch]
