title: Clashsoft
email: clashsoft@example.com
description: >-
  Welcome to my personal site!
baseurl: ""
url: "https://www.clashsoft.de"
twitter_username: Clashsoft
github_username: Clashsoft
remote_theme: jonaharagon/jekyll-bootstrap-theme
markdown: GFM
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-remote-theme
